[package]
edition = "2021"
name = "bitfield-impl"
publish = false
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
# TODO
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "1.0", features = ["parsing", "full"]}
