[package]
autotests = false
edition = "2021"
name = "bitfield"
publish = false
version = "0.0.0"

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = {version = "1.0.49", features = ["diff"]}

[dependencies]
bitfield-impl = {path = "impl"}